services:
  database:
    build: ./database
    env_file:
      - ./database/.env
    ports:
      - "3306:3306"
    volumes:
      - ./database/conf.d:/etc/mysql/conf.d
      - ./database/initdb.d:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
      
volumes:
  db-data:
